name: Make Release

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    
    - name: Run tests
      run: poetry run pytest

  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    needs:
      - test
    
    outputs:
      changes: ${{ steps.changelog.outputs.changes }}
      current-version: ${{ steps.bump.outputs.current-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Bump version
        id: bump
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"                              
          git config --global user.name "github-actions[bot]" 
          echo "previous-version=$(poetry run bump-my-version show current_version)" >> $GITHUB_OUTPUT
          poetry run bump-my-version bump ${{ github.event.inputs.bump-type }}
          echo "current-version=$(poetry run bump-my-version show current_version)" >> $GITHUB_OUTPUT
          git push --tags

      - uses: requarks/changelog-action@v1
        id: changelog
        with:
          token: ${{ github.token }}
          tag: 'v${{ steps.bump.outputs.current-version }}'

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version: ${{ steps.bump.outputs.previous-version }} → ${{ steps.bump.outputs.current-version }}"

      - name: Update tag
        run: |
          git tag -d v${{ steps.bump.outputs.current-version }}
          git tag v${{ steps.bump.outputs.current-version}}
          git push --force --tags origin main

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: 
      - test
      - bump-version

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'v${{ needs.bump-version.outputs.current-version }}'
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      
      - name: Build wheel
        run: poetry build

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: 'v${{ needs.bump-version.outputs.current-version }}'
          name: 'v${{ needs.bump-version.outputs.current-version }}'
          body: ${{ needs.bump-version.outputs.changes }}
          token: ${{ github.token }}
          artifacts: dist/*
